# Generated by Django 3.2.7 on 2021-09-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_survey_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='many_choice',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='text',
        ),
    ]
